-- 创建数据库
CREATE DATABASE IF NOT EXISTS ss19_shop;

-- 选择数据库
USE ss19_shop;

-- 创建会员表

CREATE TABLE IF NOT EXISTS user(
	id INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(18) NOT NULL unique,
	password CHAR(32) NOT NULL,
	level  TINYINT NOT NULL DEFAULT 0, -- 0普通会员   1 普通管理员 2 超级管理员 3-禁止
	addtime  INT UNSIGNED NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS user_u(
	id INT AUTO_INCREMENT PRIMARY KEY,
	uid INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(18) NOT NULL ,
	age TINYINT UNSIGNED NOT NULL ,
	sex TINYINT UNSIGNED NOT NULL ,
	phone CHAR(11) ,
	email VARCHAR(60),
	pic   VARCHAR(255),
	hobby   VARCHAR(255),
	marry   TINYINT UNSIGNED,
	address   VARCHAR(255)
	
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


--关联查询的sql语句
SELECT  u.			FROM user u INNER JOIN user_u r ON u.id=r.id AND u.id=2;


--超链接数据库
CREATE TABLE IF NOT EXISTS hyperlink(
	id INT  AUTO_INCREMENT PRIMARY KEY,
	linkname VARCHAR(18) NOT NULL,
	linkadd	 VARCHAR(255) NOT NULL,
	display INT NOT NULL DEFAULT 0
)ENGINE=InnoDB DEFAULT CHARSET=utf8;



--修改表结构
ALTER TABLE hyperlink MODIFY linkname VARCHAR(18) NOT NULL unique;
ALTER TABLE user_home MODIFY username VARCHAR(18) NOT NULL unique;
ALTER TABLE user_address ADD code CHAR(6) NOT NULL ;
ALTER TABLE orders_u ADD pic VARCHAR(255) NOT NULL ;

--创建商品的字段名

CREATE TABLE IF NOT EXISTS goods(
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	typeid INT NOT NULL,
	price DECIMAL(8,2) NOT NULL,
	store INT  NOT NULL,
	sales INT  NOT NULL DEFAULT 0 ,
	pic  VARCHAR(255) NOT NULL,
	`status` TINYINT NOT NULL DEFAULT 0,
	company VARCHAR(255) NOT NULL ,
	descr VARCHAR(255) 
)ENGINE =InnoDB	 DEFAULT CHARSET=utf8; 

--需要创建一个前台页面用户的数据库

CREATE TABLE IF NOT EXISTS user_home(
	id INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(18) NOT NULL unique,
	phone CHAR(11) ,
	sex TINYINT UNSIGNED NOT NULL ,
	password CHAR(32) NOT NULL,
	email VARCHAR(60),
	pic   VARCHAR(255)
		
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

--需要创建订单表
CREATE TABLE IF NOT EXISTS orders(
	id INT AUTO_INCREMENT PRIMARY KEY,
	uid INT NOT NULL ,
	linkname VARCHAR(30) NOT NULL ,
	address VARCHAR(255) NOT NULL ,
	phone CHAR(11) NOT NULL ,
	code CHAR(6) NOT NULL ,
	total DECIMAL(8,2) NOT NULL ,
	status TINYINT	
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

--需要创建订单详情表
CREATE TABLE IF NOT EXISTS orders_u(
	id INT AUTO_INCREMENT PRIMARY KEY,
	oid INT NOT NULL ,
	gid INT NOT NULL,
	gname VARCHAR(255) NOT NULL,
	price DECIMAL(8,2) NOT NULL ,
	gnum INT NOT NULL,
	uid INT NOT NULL 
	
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

--创建一个储存用户收货联系人的表
CREATE TABLE IF NOT EXISTS user_address(
	id INT AUTO_INCREMENT PRIMARY KEY,
	uid INT NOT NULL,
	addname VARCHAR(18) NOT NULL ,
	phone CHAR(11) NOT NULL,
	address   VARCHAR(255) NOT NULL

	
)ENGINE=InnoDB DEFAULT CHARSET=utf8;